package starter

import screeps.api.RESOURCE_BIOMASS
import screeps.api.RESOURCE_CATALYST
import screeps.api.RESOURCE_CATALYZED_GHODIUM_ACID
import screeps.api.RESOURCE_CATALYZED_GHODIUM_ALKALIDE
import screeps.api.RESOURCE_CATALYZED_KEANIUM_ACID
import screeps.api.RESOURCE_CATALYZED_KEANIUM_ALKALIDE
import screeps.api.RESOURCE_CATALYZED_LEMERGIUM_ACID
import screeps.api.RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE
import screeps.api.RESOURCE_CATALYZED_UTRIUM_ACID
import screeps.api.RESOURCE_CATALYZED_UTRIUM_ALKALIDE
import screeps.api.RESOURCE_CATALYZED_ZYNTHIUM_ACID
import screeps.api.RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE
import screeps.api.RESOURCE_FIXTURES
import screeps.api.RESOURCE_FRAME
import screeps.api.RESOURCE_GHODIUM
import screeps.api.RESOURCE_GHODIUM_ACID
import screeps.api.RESOURCE_GHODIUM_ALKALIDE
import screeps.api.RESOURCE_GHODIUM_HYDRIDE
import screeps.api.RESOURCE_GHODIUM_OXIDE
import screeps.api.RESOURCE_HYDRAULICS
import screeps.api.RESOURCE_HYDROGEN
import screeps.api.RESOURCE_HYDROXIDE
import screeps.api.RESOURCE_KEANIUM
import screeps.api.RESOURCE_KEANIUM_ACID
import screeps.api.RESOURCE_KEANIUM_ALKALIDE
import screeps.api.RESOURCE_KEANIUM_HYDRIDE
import screeps.api.RESOURCE_KEANIUM_OXIDE
import screeps.api.RESOURCE_LEMERGIUM
import screeps.api.RESOURCE_LEMERGIUM_ACID
import screeps.api.RESOURCE_LEMERGIUM_ALKALIDE
import screeps.api.RESOURCE_LEMERGIUM_HYDRIDE
import screeps.api.RESOURCE_LEMERGIUM_OXIDE
import screeps.api.RESOURCE_MACHINE
import screeps.api.RESOURCE_METAL
import screeps.api.RESOURCE_MIST
import screeps.api.RESOURCE_OXYGEN
import screeps.api.RESOURCE_SILICON
import screeps.api.RESOURCE_TUBE
import screeps.api.RESOURCE_UTRIUM
import screeps.api.RESOURCE_UTRIUM_ACID
import screeps.api.RESOURCE_UTRIUM_ALKALIDE
import screeps.api.RESOURCE_UTRIUM_HYDRIDE
import screeps.api.RESOURCE_UTRIUM_LEMERGITE
import screeps.api.RESOURCE_UTRIUM_OXIDE
import screeps.api.RESOURCE_ZYNTHIUM
import screeps.api.RESOURCE_ZYNTHIUM_ACID
import screeps.api.RESOURCE_ZYNTHIUM_ALKALIDE
import screeps.api.RESOURCE_ZYNTHIUM_HYDRIDE
import screeps.api.RESOURCE_ZYNTHIUM_KEANITE
import screeps.api.RESOURCE_ZYNTHIUM_OXIDE
import screeps.api.TradableConstant

/**
 *
 *
 * @author zakharchuk
 * @since 29.03.2020
 */

val SIMPLE_MINERALS = arrayOf(
        RESOURCE_OXYGEN, RESOURCE_HYDROGEN,
        RESOURCE_ZYNTHIUM, RESOURCE_LEMERGIUM,
        RESOURCE_UTRIUM, RESOURCE_KEANIUM,
        RESOURCE_CATALYST
)

val BASE_COMPOUNDS = arrayOf(
        RESOURCE_HYDROXIDE, RESOURCE_ZYNTHIUM_KEANITE,
        RESOURCE_UTRIUM_LEMERGITE, RESOURCE_GHODIUM
)

val TIER_1_COMPOUNDS = arrayOf(
        RESOURCE_UTRIUM_HYDRIDE, RESOURCE_UTRIUM_OXIDE,
        RESOURCE_KEANIUM_HYDRIDE, RESOURCE_KEANIUM_OXIDE,
        RESOURCE_LEMERGIUM_HYDRIDE, RESOURCE_LEMERGIUM_OXIDE,
        RESOURCE_ZYNTHIUM_HYDRIDE, RESOURCE_ZYNTHIUM_OXIDE,
        RESOURCE_GHODIUM_HYDRIDE, RESOURCE_GHODIUM_OXIDE
)

val TIER_2_COMPOUNDS = arrayOf(
        RESOURCE_UTRIUM_ACID, RESOURCE_UTRIUM_ALKALIDE,
        RESOURCE_KEANIUM_ACID, RESOURCE_KEANIUM_ALKALIDE,
        RESOURCE_LEMERGIUM_ACID, RESOURCE_LEMERGIUM_ALKALIDE,
        RESOURCE_ZYNTHIUM_ACID, RESOURCE_ZYNTHIUM_ALKALIDE,
        RESOURCE_GHODIUM_ACID, RESOURCE_GHODIUM_ALKALIDE
)

val TIER_3_COMPOUNDS = arrayOf(
        RESOURCE_CATALYZED_UTRIUM_ACID, RESOURCE_CATALYZED_UTRIUM_ALKALIDE,
        RESOURCE_CATALYZED_KEANIUM_ACID, RESOURCE_CATALYZED_KEANIUM_ALKALIDE,
        RESOURCE_CATALYZED_LEMERGIUM_ACID, RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE,
        RESOURCE_CATALYZED_ZYNTHIUM_ACID, RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE,
        RESOURCE_CATALYZED_GHODIUM_ACID, RESOURCE_CATALYZED_GHODIUM_ALKALIDE
)

val ALL_COMPOUNDS = BASE_COMPOUNDS.plus(TIER_1_COMPOUNDS).plus(TIER_2_COMPOUNDS).plus(TIER_3_COMPOUNDS)

val ALL_COMPOUNDS_WITH_MINERALS = ALL_COMPOUNDS.plus(SIMPLE_MINERALS)

val SIMPLE_COMMODITIES = arrayOf(
        RESOURCE_METAL, RESOURCE_BIOMASS,
        RESOURCE_SILICON, RESOURCE_MIST
)

val MECHANICAL_CHAIN = arrayOf(
        RESOURCE_TUBE, RESOURCE_FIXTURES, RESOURCE_FRAME, RESOURCE_HYDRAULICS, RESOURCE_MACHINE
)

fun TradableConstant.img(): String {
    return """<img src="https://s3.amazonaws.com/static.screeps.com/upload/mineral-icons/$this.png">"""
}

val STORAGE_COMPOUNDS_AMOUNT = 10_000